ALTER TABLE posts
ADD COLUMN IF NOT EXISTS summary VARCHAR(300);

UPDATE posts
SET summary = ''
WHERE summary IS NULL OR BTRIM(summary) = '';

ALTER TABLE posts
ALTER COLUMN summary SET DEFAULT '',
ALTER COLUMN summary SET NOT NULL;
